version: '1'

services:
  log-viewer-back:
    build: ./log-viewer-back
    container_name: log-viewer-back
    environment:
      - ENV=development
    ports:
      - 5500:5500

  log-viewer-front:
    build: ./log-viewer-front
    container_name: log-viewer-front
    ports:
      - 3000:80
    links:
      - log-viewer-back
